# Generated by Django 4.2.6 on 2024-05-17 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Invalid username', regex='^[a-zA-Z0-9][a-zA-Z0-9_]*$')])),
                ('password', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Invalid password', regex='^[A-Za-z\\d!@#$%^&*()_+]+$')])),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+\\d{1,3} \\(\\d{3}\\) \\d{3}-\\d{4}$')])),
                ('experience', models.CharField(blank=True, null=True)),
                ('is_executor', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
