# Generated by Django 4.2.6 on 2024-05-17 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_user_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(editable=False, max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Invalid password', regex='^[A-Za-z\\d!@#$%^&*()_+]+$')]),
        ),
    ]
