# Generated by Django 4.2.6 on 2024-05-17 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_user_contact_phone_number_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+7\\d{10}$')]),
        ),
    ]
